"""baseline — stamp of live schema (no-op)

Revision ID: 0001_baseline
Revises:
Create Date: baseline only

The live Aiven Postgres database already has all tables (created via
Base.metadata.create_all). This revision is intentionally EMPTY: it exists
only so `alembic stamp head` can record the current schema state as the
migration baseline without creating, altering, or dropping any tables.
Future schema changes get real autogenerated revisions on top of this.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Baseline no-op: live DB already matches models. Do not create tables here.
    pass


def downgrade() -> None:
    # Baseline no-op: nothing to revert.
    pass
