import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Text,
  Button,
  Hr,
} from "@react-email/components";

interface QuoteEmailProps {
  businessName: string;
  quoteNumber: string;
  customerName: string;
  title: string;
  items: Array<{ description: string; quantity: number; unitPrice: number; total: number }>;
  subtotal: number;
  vatRate: number;
  vatAmount: number;
  total: number;
  validUntil: string;
  quoteUrl: string;
  notes?: string;
}

export default function QuoteEmail({
  businessName = "Your Business",
  quoteNumber = "Q-000000",
  customerName = "Customer",
  title = "Service Quote",
  items = [],
  subtotal = 0,
  vatRate = 20,
  vatAmount = 0,
  total = 0,
  validUntil = "",
  quoteUrl = "#",
  notes = "",
}: QuoteEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>Quote {quoteNumber} from {businessName} — {title}</Preview>
      <Body style={body}>
        <Container style={container}>
          <Heading style={heading}>{title}</Heading>
          <Text style={text}>Hi {customerName},</Text>
          <Text style={text}>
            Here&apos;s your quote from {businessName}. Please review the details below.
          </Text>

          <Section style={tableSection}>
            <table style={table}>
              <thead>
                <tr>
                  <th style={th}>Description</th>
                  <th style={thRight}>Qty</th>
                  <th style={thRight}>Price</th>
                  <th style={thRight}>Total</th>
                </tr>
              </thead>
              <tbody>
                {items.map((item, i) => (
                  <tr key={i}>
                    <td style={td}>{item.description}</td>
                    <td style={tdRight}>{item.quantity}</td>
                    <td style={tdRight}>£{item.unitPrice.toFixed(2)}</td>
                    <td style={tdRight}>£{item.total.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Section>

          <Section style={totalsSection}>
            <table style={totalsTable}>
              <tr>
                <td style={totalLabel}>Subtotal</td>
                <td style={totalValue}>£{subtotal.toFixed(2)}</td>
              </tr>
              <tr>
                <td style={totalLabel}>VAT ({vatRate}%)</td>
                <td style={totalValue}>£{vatAmount.toFixed(2)}</td>
              </tr>
              <tr>
                <td style={totalLabelBold}>Total</td>
                <td style={totalValueBold}>£{total.toFixed(2)}</td>
              </tr>
            </table>
          </Section>

          {validUntil && (
            <Text style={validText}>Valid until: {validUntil}</Text>
          )}

          {notes && (
            <Section style={notesSection}>
              <Text style={notesLabel}>Notes:</Text>
              <Text style={notesText}>{notes}</Text>
            </Section>
          )}

          <Section style={buttonSection}>
            <Button href={quoteUrl} style={button}>
              Accept Quote
            </Button>
          </Section>

          <Hr style={hr} />
          <Text style={footer}>
            Quote generated by VoiceField. This quote is valid until {validUntil}.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

const body = { backgroundColor: "#f6f9fc", fontFamily: "system-ui, sans-serif" };
const container = { maxWidth: "600px", margin: "0 auto", padding: "20px" };
const heading = { fontSize: "24px", fontWeight: "bold", color: "#1a1a2e" as const };
const text = { fontSize: "14px", color: "#4a5568" as const, lineHeight: "1.5" };
const tableSection = { marginTop: "24px" };
const table = { width: "100%", borderCollapse: "collapse" as const };
const th = { textAlign: "left" as const, padding: "12px 8px", borderBottom: "2px solid #e2e8f0", fontSize: "12px", color: "#718096", textTransform: "uppercase" as const };
const thRight = { ...th, textAlign: "right" as const };
const td = { padding: "12px 8px", borderBottom: "1px solid #e2e8f0", fontSize: "14px" };
const tdRight = { ...td, textAlign: "right" as const };
const totalsSection = { marginTop: "16px" };
const totalsTable = { width: "100%", maxWidth: "250px", marginLeft: "auto" };
const totalLabel = { padding: "4px 8px", fontSize: "14px", color: "#4a5568" as const };
const totalValue = { padding: "4px 8px", fontSize: "14px", textAlign: "right" as const };
const totalLabelBold = { ...totalLabel, fontWeight: "bold", borderTop: "2px solid #1a1a2e", paddingTop: "8px" };
const totalValueBold = { ...totalValue, fontWeight: "bold", color: "#6b21a8" as const, borderTop: "2px solid #1a1a2e", paddingTop: "8px" };
const validText = { fontSize: "14px", color: "#e53e3e", fontWeight: "bold" as const, marginTop: "16px" };
const notesSection = { marginTop: "16px", padding: "12px", backgroundColor: "#f7fafc", borderRadius: "8px" };
const notesLabel = { fontSize: "12px", fontWeight: "bold", color: "#4a5568" as const };
const notesText = { fontSize: "14px", color: "#4a5568" as const, marginTop: "4px" };
const buttonSection = { marginTop: "24px", textAlign: "center" as const };
const button = { backgroundColor: "#6b21a8", color: "#ffffff", padding: "12px 24px", borderRadius: "8px", fontSize: "14px", fontWeight: "bold", textDecoration: "none" };
const hr = { border: "none", borderTop: "1px solid #e2e8f0", margin: "24px 0" };
const footer = { fontSize: "12px", color: "#a0aec0", textAlign: "center" as const };
