import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

interface InvoiceData {
  invoiceNumber: string;
  businessName: string;
  businessAddress: string;
  businessPhone: string;
  businessEmail: string;
  customerName: string;
  customerAddress: string;
  items: Array<{ description: string; quantity: number; unitPrice: number; total: number }>;
  subtotal: number;
  vatRate: number;
  vatAmount: number;
  total: number;
  dueDate: string;
  notes?: string;
}

export async function generateInvoicePDF(data: InvoiceData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const page = pdfDoc.addPage([595, 842]); // A4

  let y = 780;

  // Header
  page.drawText("INVOICE", {
    x: 50,
    y,
    size: 28,
    font: fontBold,
    color: rgb(0.42, 0.13, 0.66),
  });

  page.drawText(data.invoiceNumber, {
    x: 400,
    y,
    size: 14,
    font: font,
    color: rgb(0.3, 0.3, 0.3),
  });

  y -= 40;

  // Business info
  page.drawText(data.businessName, { x: 50, y, size: 12, font: fontBold });
  y -= 18;
  page.drawText(data.businessAddress, { x: 50, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 14;
  page.drawText(`Phone: ${data.businessPhone}`, { x: 50, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 14;
  page.drawText(`Email: ${data.businessEmail}`, { x: 50, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });

  y -= 40;

  // Customer info
  page.drawText("BILL TO:", { x: 400, y, size: 10, font: fontBold, color: rgb(0.4, 0.4, 0.4) });
  y -= 16;
  page.drawText(data.customerName, { x: 400, y, size: 12, font: fontBold });
  y -= 16;
  page.drawText(data.customerAddress, { x: 400, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });

  y -= 40;

  // Table header
  page.drawRectangle({
    x: 50,
    y: y - 5,
    width: 495,
    height: 22,
    color: rgb(0.92, 0.92, 0.95),
  });

  page.drawText("Description", { x: 55, y, size: 9, font: fontBold });
  page.drawText("Qty", { x: 320, y, size: 9, font: fontBold });
  page.drawText("Price", { x: 380, y, size: 9, font: fontBold });
  page.drawText("Total", { x: 470, y, size: 9, font: fontBold });

  y -= 25;

  // Table rows
  for (const item of data.items) {
    page.drawText(item.description, { x: 55, y, size: 10, font });
    page.drawText(item.quantity.toString(), { x: 325, y, size: 10, font });
    page.drawText(`£${item.unitPrice.toFixed(2)}`, { x: 380, y, size: 10, font });
    page.drawText(`£${item.total.toFixed(2)}`, { x: 470, y, size: 10, font });
    y -= 18;

    // Separator line
    page.drawLine({
      start: { x: 50, y: y + 10 },
      end: { x: 545, y: y + 10 },
      thickness: 0.5,
      color: rgb(0.9, 0.9, 0.9),
    });
  }

  y -= 20;

  // Totals
  page.drawText("Subtotal:", { x: 380, y, size: 10, font });
  page.drawText(`£${data.subtotal.toFixed(2)}`, { x: 470, y, size: 10, font });

  y -= 18;
  page.drawText(`VAT (${data.vatRate}%):`, { x: 380, y, size: 10, font });
  page.drawText(`£${data.vatAmount.toFixed(2)}`, { x: 470, y, size: 10, font });

  y -= 22;
  // Total line
  page.drawLine({
    start: { x: 375, y: y + 8 },
    end: { x: 545, y: y + 8 },
    thickness: 1,
    color: rgb(0.42, 0.13, 0.66),
  });

  page.drawText("Total:", { x: 380, y, size: 12, font: fontBold });
  page.drawText(`£${data.total.toFixed(2)}`, {
    x: 460,
    y,
    size: 14,
    font: fontBold,
    color: rgb(0.42, 0.13, 0.66),
  });

  y -= 40;

  // Due date
  page.drawText(`Due Date: ${data.dueDate}`, {
    x: 50,
    y,
    size: 10,
    font,
    color: rgb(0.9, 0.2, 0.2),
  });

  // Notes
  if (data.notes) {
    y -= 30;
    page.drawText("Notes:", { x: 50, y, size: 10, font: fontBold });
    y -= 16;
    page.drawText(data.notes, { x: 50, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  }

  // Footer
  page.drawText("Generated by Allo", {
    x: 200,
    y: 50,
    size: 8,
    font,
    color: rgb(0.7, 0.7, 0.7),
  });

  return pdfDoc.save();
}

export async function generateQuotePDF(data: InvoiceData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const page = pdfDoc.addPage([595, 842]);

  let y = 780;

  page.drawText("QUOTE", {
    x: 50,
    y,
    size: 28,
    font: fontBold,
    color: rgb(0.42, 0.13, 0.66),
  });

  page.drawText(data.invoiceNumber, {
    x: 400,
    y,
    size: 14,
    font,
    color: rgb(0.3, 0.3, 0.3),
  });

  y -= 40;
  page.drawText(data.businessName, { x: 50, y, size: 12, font: fontBold });
  y -= 18;
  page.drawText(data.businessAddress, { x: 50, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 14;
  page.drawText(`Phone: ${data.businessPhone}`, { x: 50, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });

  y -= 40;
  page.drawText("PREPARED FOR:", { x: 400, y, size: 10, font: fontBold, color: rgb(0.4, 0.4, 0.4) });
  y -= 16;
  page.drawText(data.customerName, { x: 400, y, size: 12, font: fontBold });
  y -= 16;
  page.drawText(data.customerAddress, { x: 400, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });

  y -= 40;

  // Table
  page.drawRectangle({ x: 50, y: y - 5, width: 495, height: 22, color: rgb(0.92, 0.92, 0.95) });
  page.drawText("Description", { x: 55, y, size: 9, font: fontBold });
  page.drawText("Qty", { x: 320, y, size: 9, font: fontBold });
  page.drawText("Price", { x: 380, y, size: 9, font: fontBold });
  page.drawText("Total", { x: 470, y, size: 9, font: fontBold });
  y -= 25;

  for (const item of data.items) {
    page.drawText(item.description, { x: 55, y, size: 10, font });
    page.drawText(item.quantity.toString(), { x: 325, y, size: 10, font });
    page.drawText(`£${item.unitPrice.toFixed(2)}`, { x: 380, y, size: 10, font });
    page.drawText(`£${item.total.toFixed(2)}`, { x: 470, y, size: 10, font });
    y -= 18;
  }

  y -= 10;
  page.drawText("Subtotal:", { x: 380, y, size: 10, font });
  page.drawText(`£${data.subtotal.toFixed(2)}`, { x: 470, y, size: 10, font });
  y -= 18;
  page.drawText(`VAT (${data.vatRate}%):`, { x: 380, y, size: 10, font });
  page.drawText(`£${data.vatAmount.toFixed(2)}`, { x: 470, y, size: 10, font });
  y -= 22;
  page.drawLine({ start: { x: 375, y: y + 8 }, end: { x: 545, y: y + 8 }, thickness: 1, color: rgb(0.42, 0.13, 0.66) });
  page.drawText("Total:", { x: 380, y, size: 12, font: fontBold });
  page.drawText(`£${data.total.toFixed(2)}`, { x: 460, y, size: 14, font: fontBold, color: rgb(0.42, 0.13, 0.66) });

  y -= 40;
  page.drawText(`Valid until: ${data.dueDate}`, { x: 50, y, size: 10, font, color: rgb(0.9, 0.2, 0.2) });

  if (data.notes) {
    y -= 30;
    page.drawText("Notes:", { x: 50, y, size: 10, font: fontBold });
    y -= 16;
    page.drawText(data.notes, { x: 50, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  }

  page.drawText("Generated by Allo", { x: 200, y: 50, size: 8, font, color: rgb(0.7, 0.7, 0.7) });

  return pdfDoc.save();
}
